services:
  frontend:
    container_name: client
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "33333:33333"
    volumes:
      - ./:/client
      - /client/node_modules/
      - /client/.parcel-cache/
    # command: [ "parcel", "ui/index.html -p 8080 --hmr-port 33333" ]
    command: [ "npm", "start" ]
