services:
  frontend:
    container_name: client
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
      - "33333:33333"
    volumes:
      - ./:/client
      - /client/node_modules/
      - /client/.parcel-cache/
    command: [ "npm", "start" ]
