services:
  nginx:
    container_name: proxy
    image: nginx:stable-alpine
    depends_on:
      - "client"
      - "api"
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d/
      - ./docker/nginx/includes:/etc/nginx/includes/
    networks:
      - site-network

  client:
    depends_on:
      - "api"
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    networks:
      - site-network

  api:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    networks:
      - site-network

networks:
  site-network:
    name: site-network
    driver: bridge
