services:
  backend:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./:/api
    # command: air
    tty: true
